/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author ilya
 */
public class ModEditor extends javax.swing.JFrame {

 /**
  * Creates new form ModEditor
  */
 public ModEditor () {
  initComponents();
 }

 /**
  * This method is called from within the constructor to
  * initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is
  * always regenerated by the Form Editor.
  */
 @SuppressWarnings( "unchecked" )
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jLabel1 = new javax.swing.JLabel();
  jTextField1 = new javax.swing.JTextField();
  jButton1 = new javax.swing.JButton();
  jScrollPane1 = new javax.swing.JScrollPane();
  items = new javax.swing.JTable();
  jScrollPane2 = new javax.swing.JScrollPane();
  jTable2 = new javax.swing.JTable();
  jScrollPane3 = new javax.swing.JScrollPane();
  jTable3 = new javax.swing.JTable();
  jButton2 = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  jLabel1.setText("Name:");

  jButton1.setText("Generate option file for actions");

  items.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "I name", "S name", "Durability", "Model", "Type", "Speed for designed blocks", "Speed for other blocks"
   }
  ) {
   Class[] types = new Class [] {
    java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
   };

   public Class getColumnClass(int columnIndex) {
    return types [columnIndex];
   }
  });
  items.getTableHeader().setReorderingAllowed(false);
  jScrollPane1.setViewportView(items);

  jTable2.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "B name", "S name", "Durability", "Model", "Dictionary", "Speed for designed tools", "Speed for other"
   }
  ));
  jTable2.getTableHeader().setReorderingAllowed(false);
  jScrollPane2.setViewportView(jTable2);

  jTable3.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "Type", "Заголовок 2", "Elements (separate by ' , ')"
   }
  ));
  jTable3.getTableHeader().setReorderingAllowed(false);
  jScrollPane3.setViewportView(jTable3);

  jButton2.setText("Save");

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addGroup(layout.createSequentialGroup()
      .addComponent(jLabel1)
      .addGap(39, 39, 39)
      .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jButton2)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(jButton1))
     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel1)
     .addComponent(jButton1)
     .addComponent(jButton2))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 /**
  * @param args the command line arguments
  */
 public static void main ( String args[] ) {
  /*
   * Set the Nimbus look and feel
   */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
   * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
   */
  try {
   for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
           getInstalledLookAndFeels() ) {
    if ( "Nimbus".equals(info.getName()) ) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch ( ClassNotFoundException ex ) {
   java.util.logging.Logger.getLogger(ModEditor.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( InstantiationException ex ) {
   java.util.logging.Logger.getLogger(ModEditor.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( IllegalAccessException ex ) {
   java.util.logging.Logger.getLogger(ModEditor.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
   java.util.logging.Logger.getLogger(ModEditor.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  }
        //</editor-fold>

  /*
   * Create and display the form
   */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run () {
    new ModEditor().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JTable items;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JScrollPane jScrollPane2;
 private javax.swing.JScrollPane jScrollPane3;
 private javax.swing.JTable jTable2;
 private javax.swing.JTable jTable3;
 private javax.swing.JTextField jTextField1;
 // End of variables declaration//GEN-END:variables
}
