/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author ilya
 */
public class NewJFrame extends javax.swing.JFrame {

 /**
  * Creates new form NewJFrame
  */
 public NewJFrame () {
  initComponents();
 }

 /**
  * This method is called from within the constructor to
  * initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is
  * always regenerated by the Form Editor.
  */
 @SuppressWarnings( "unchecked" )
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jScrollPane3 = new javax.swing.JScrollPane();
  modsList = new javax.swing.JList();
  jScrollPane4 = new javax.swing.JScrollPane();
  coreList = new javax.swing.JList();
  start = new javax.swing.JButton();
  options = new javax.swing.JButton();
  modelEdit = new javax.swing.JButton();
  mods = new javax.swing.JButton();
  log = new javax.swing.JButton();
  levelEdit = new javax.swing.JButton();
  loginLabel = new javax.swing.JLabel();
  passLabel = new javax.swing.JLabel();
  passField = new javax.swing.JPasswordField();
  loginField = new javax.swing.JTextField();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  jScrollPane3.setViewportView(modsList);

  jScrollPane4.setViewportView(coreList);

  start.setLabel("Start Game");
  start.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    startMouseClicked(evt);
   }
  });

  options.setActionCommand("Options");
  options.setAutoscrolls(true);
  options.setLabel("Options");

  modelEdit.setLabel("Model Editor");

  mods.setLabel("Mods Editor");

  log.setLabel("Log manager");

  levelEdit.setLabel("Level Editor");

  loginLabel.setText("Логин:");

  passLabel.setText("Пароль:");

  passField.setText("test");

  loginField.setText("test");

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
       .addComponent(loginLabel))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addComponent(passLabel)
        .addGap(0, 0, Short.MAX_VALUE))
       .addComponent(passField)))
     .addGroup(layout.createSequentialGroup()
      .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(mods, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addComponent(levelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(modelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(layout.createSequentialGroup()
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(start)
        .addComponent(options))
       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(log)
        .addComponent(mods))
       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(levelEdit)
        .addComponent(modelEdit))
       .addGap(47, 47, 47)
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(passLabel)
        .addComponent(loginLabel))
       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
  // TODO add your handling code here:
 }//GEN-LAST:event_startMouseClicked

 /**
  * @param args the command line arguments
  */
 public static void main ( String args[] ) {
  /*
   * Set the Nimbus look and feel
   */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
   * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
   */
  try {
   for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
           getInstalledLookAndFeels() ) {
    if ( "Nimbus".equals(info.getName()) ) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch ( ClassNotFoundException ex ) {
   java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( InstantiationException ex ) {
   java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( IllegalAccessException ex ) {
   java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
   java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  }
        //</editor-fold>

  /*
   * Create and display the form
   */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run () {
    new NewJFrame().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JList coreList;
 private javax.swing.JScrollPane jScrollPane3;
 private javax.swing.JScrollPane jScrollPane4;
 private javax.swing.JButton levelEdit;
 private javax.swing.JButton log;
 private javax.swing.JTextField loginField;
 private javax.swing.JLabel loginLabel;
 private javax.swing.JButton modelEdit;
 private javax.swing.JButton mods;
 private javax.swing.JList modsList;
 private javax.swing.JButton options;
 private javax.swing.JPasswordField passField;
 private javax.swing.JLabel passLabel;
 private javax.swing.JButton start;
 // End of variables declaration//GEN-END:variables
}
