/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mods;

/**
 *
 * @author ilya
 */
public class Item extends javax.swing.JFrame {

 /**
  * Creates new form Items
  */
 public Item () {
  initComponents();
 }

 /**
  * This method is called from within the constructor to
  * initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is
  * always regenerated by the Form Editor.
  */
 @SuppressWarnings( "unchecked" )
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jScrollPane1 = new javax.swing.JScrollPane();
  items = new javax.swing.JTable();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  items.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "I name", "S name", "Durability", "Model", "Type", "Speed for designed blocks", "Speed for other blocks"
   }
  ) {
   Class[] types = new Class [] {
    java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
   };

   public Class getColumnClass(int columnIndex) {
    return types [columnIndex];
   }
  });
  items.setName(""); // NOI18N
  items.getTableHeader().setReorderingAllowed(false);
  jScrollPane1.setViewportView(items);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 790, Short.MAX_VALUE)
   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
     .addGap(145, 145, 145)
     .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
     .addGap(145, 145, 145)))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGap(0, 433, Short.MAX_VALUE)
   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
     .addGap(21, 21, 21)
     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addContainerGap(262, Short.MAX_VALUE)))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 /**
  * @param args the command line arguments
  */
 public static void main ( String args[] ) {
  /*
   * Set the Nimbus look and feel
   */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
   * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
   */
  try {
   for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
           getInstalledLookAndFeels() ) {
    if ( "Nimbus".equals(info.getName()) ) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch ( ClassNotFoundException ex ) {
   java.util.logging.Logger.getLogger(Item.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( InstantiationException ex ) {
   java.util.logging.Logger.getLogger(Item.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( IllegalAccessException ex ) {
   java.util.logging.Logger.getLogger(Item.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
   java.util.logging.Logger.getLogger(Item.class.getName()).log(
           java.util.logging.Level.SEVERE , null , ex);
  }
  //</editor-fold>
  //</editor-fold>

  /*
   * Create and display the form
   */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run () {
    new Item().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JTable items;
 private javax.swing.JScrollPane jScrollPane1;
 // End of variables declaration//GEN-END:variables
}
